apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk
  labels:
    app: php
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
